version: '3'
services:
  app:
    image: next-prisma-docker
    build:
      context: .
      dockerfile: Dockerfile
      target: deploy
    ports:
      - 3000:3000
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    expose:
      - "5432"
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: postgresVolum
